/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_byui_PET_gps_GPS */

#ifndef _Included_edu_byui_PET_gps_GPS
#define _Included_edu_byui_PET_gps_GPS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_byui_PET_gps_GPS
 * Method:    createGPS
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_byui_PET_gps_GPS_createGPS
  (JNIEnv *, jobject);

/*
 * Class:     edu_byui_PET_gps_GPS
 * Method:    getGPSData
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_byui_PET_gps_GPS_getGPSData
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
