/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_byui_PET_camera_JNICamera */

#ifndef _Included_edu_byui_PET_camera_JNICamera
#define _Included_edu_byui_PET_camera_JNICamera
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_byui_PET_camera_JNICamera
 * Method:    createCamera
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_byui_PET_camera_JNICamera_createCamera
  (JNIEnv *env, jobject jobj);

/*
 * Class:     edu_byui_PET_camera_JNICamera
 * Method:    getCameraData
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_byui_PET_camera_JNICamera_getCameraData
  (JNIEnv *env, jobject jobj, jlong ptr, jlong size);

/*
 * Class:     edu_byui_PET_camera_JNICamera
 * Method:    getXResolution
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_edu_byui_PET_camera_JNICamera_getXResolution
  (JNIEnv *env, jobject jobj, jlong ptr);

/*
 * Class:     edu_byui_PET_camera_JNICamera
 * Method:    getYResolution
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_edu_byui_PET_camera_JNICamera_getYResolution
  (JNIEnv *env, jobject jobj, jlong ptr);

#ifdef __cplusplus
}
#endif
#endif
