/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_byui_PET_camera_BaslerA311JNI */

#ifndef _Included_edu_byui_PET_camera_BaslerA311JNI
#define _Included_edu_byui_PET_camera_BaslerA311JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_byui_PET_camera_BaslerA311JNI
 * Method:    createCamera
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_byui_PET_camera_BaslerA311JNI_createCamera
  (JNIEnv *, jobject);

/*
 * Class:     edu_byui_PET_camera_BaslerA311JNI
 * Method:    getCameraData
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_byui_PET_camera_BaslerA311JNI_getCameraData
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_byui_PET_camera_BaslerA311JNI
 * Method:    getXResolution
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_edu_byui_PET_camera_BaslerA311JNI_getXResolution
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_byui_PET_camera_BaslerA311JNI
 * Method:    getYResolution
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_edu_byui_PET_camera_BaslerA311JNI_getYResolution
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
